CI/CI/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;

namespace CI.Controllers
{
    public class AdminController : Controller
    {
        public IActionResult Index()
        {
            HttpContext.Session.SetInt32("Nav", 1);
            ViewBag.nav = HttpContext.Session.GetInt32("Nav");
            return View();
        }
        public IActionResult AdminCms()
        {
            HttpContext.Session.SetInt32("Nav", 2);
            ViewBag.nav = HttpContext.Session.GetInt32("Nav");
            return View();
        }
        public IActionResult AdminMission()
        {
            HttpContext.Session.SetInt32("Nav", 3);
            ViewBag.nav = HttpContext.Session.GetInt32("Nav");
            return View();
        }
        public IActionResult AdminTheme()
        {
            HttpContext.Session.SetInt32("Nav", 4);
            ViewBag.nav = HttpContext.Session.GetInt32("Nav");
            return View();
        }
        public IActionResult AdminSkills()
        {
            HttpContext.Session.SetInt32("Nav", 5);
            ViewBag.nav = HttpContext.Session.GetInt32("Nav");
            return View();
        }
        public IActionResult AdminMissionApplication()
        {
            HttpContext.Session.SetInt32("Nav", 6);
            ViewBag.nav = HttpContext.Session.GetInt32("Nav");
            return View();
        }

        public IActionResult AdminStory()
        {
            HttpContext.Session.SetInt32("Nav", 7);
            ViewBag.nav = HttpContext.Session.GetInt32("Nav");
            return View();
        }
      
      
     
        public IActionResult AdminBannerManagement()
        {
            HttpContext.Session.SetInt32("Nav", 8);
            ViewBag.nav = HttpContext.Session.GetInt32("Nav");
            return View();
        }


    }
}

CI/CI/Controllers/LoginController.cs
using CI.Models;
using CI.Repository.Interface;
using CI_Entity.CIDbContext;
using CI_Entity.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CI.Controllers
{
    public class LoginController : Controller
    {
        private readonly IUserRepository _Idb;
        
        public LoginController( IUserRepository Idb)
        {
       

            _Idb = Idb;
        }
        public IActionResult Login(long missionid ,int StoryId)
        {
            try
            {

            
            HttpContext.Session.Clear();
            return View();
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home");
            }
        }
        public IActionResult Logout()
        {
            try
            {

            
            HttpContext.Session.Clear();
            return RedirectToAction("Landingpage", "Landingpage");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Login(UserViewModel model)
        {
            try
            {

            
            if (model.MissionId !=0 && model.MissionId != null )
            {
                // var user = await _db.Users.FirstOrDefaultAsync(u => u.Email == model.Email && u.Password == model.Password);
                var user = _Idb.Login(model.Email, model.Password);
                if (user != null)
                {
                    HttpContext.Session.SetString("userID", user.UserId.ToString());
                    HttpContext.Session.SetString("Firstname", user.FirstName);
                    HttpContext.Session.SetString("useravtar", user.Avatar);
                    return RedirectToAction("Volunteering", "Volunteering", new { @id = user.UserId, missionid = model.MissionId });

                }
                else 
                { 
                    return View(); 
                }

            }
            else if( model.StoryId != null)
            {
                //var user = await _db.Users.FirstOrDefaultAsync(u => u.Email == model.Email && u.Password == model.Password);
                var user = _Idb.Login(model.Email, model.Password);
                if (user != null)
                {
                    HttpContext.Session.SetString("userID", user.UserId.ToString());
                    HttpContext.Session.SetString("Firstname", user.FirstName);
                    if(user.Avatar != null)
                    {
                        HttpContext.Session.SetString("useravtar", user.Avatar);
                    }
                 
                    return RedirectToAction("StoryDetail", "StoryListing", new { @id = user.UserId, StoryId = model.StoryId });

                }
                else
                {
                    return View();
                }
            }
            else
            {
                if (ModelState.IsValid)
                {


                  
                    //var user = await _db.Users.FirstOrDefaultAsync(u => u.Email == model.Email && u.Password == model.Password);
                    var user = _Idb.Login(model.Email, model.Password);
                    var username = model.Email.Split("@")[0];
                    if (user != null)
                    {
                        HttpContext.Session.SetString("userID", user.UserId.ToString());
                        HttpContext.Session.SetString("Firstname", user.FirstName);
                        if (user.Avatar != null)
                        {
                            HttpContext.Session.SetString("useravtar", user.Avatar);
                        }
                        TempData["Done"] = "logged in ";
                        return RedirectToAction("Landingpage", "Landingpage", new { @id = user.UserId });
                    }
                    else
                    {
                        ViewBag.Error = "Email or Password is Incorrect";

                    }
                }
                return View();

            }
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home");
            }

        }
        //    [HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Logout()
        //{
        //    await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
        //    return RedirectToAction(nameof(LoginController.Login), "Login");
        //}
    }

  
}

CI/CI/Views/Shared/Recentvolunteering_partialView.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    PaginationModel pagination = new PaginationModel();

    int pageNo = 0;

    if (ViewBag.Pagination != null)
    {
        pagination = ViewBag.Pagination;
        pageNo = pagination.CurrentPage;
    }
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <div class=" container  ">
        <div class="row">


        @foreach (var recent in ViewBag.recentvolunteered)
        {
            <div class="col-4  ">
                <a class=" ms-4 me-2 text-decoration-none text-black  ">
                    <img src="~/images/volunteer1.png" class="involveduserprofile" />
                    <label id="" class="text-center d-flex justify-content-center">@recent.username</label>
                </a>
            </div>
        }
        </div>

    </div>

    <div class="container-fluid mt-3">
        
        @if (pagination.TotalPages > 0)
        {
            <ul class="pagination justify-content-center">
                @if (pagination.CurrentPage > pagination.StartPage)
                {
                    
                    <li class="page-item">
                        <a class="page-link" onclick="recentvol(@pagination.CurrentPage - 1,' ')"></a>
                    </li>

                }

               

                @if (pagination.CurrentPage < pagination.TotalPages)
                {
                    <li class="page-item">
                        <a class="page-link" onclick="recentvol(@pagination.CurrentPage + 1,' ')"></a>
                    </li>
             
                }
            </ul>
        }
     
    </div>


</body>
</html>

CI/CI/Views/Shared/_AdminSidebar.cshtml
@{

}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
   
   
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css">
 
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css">
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.ckeditor.com/4.21.0/standard/ckeditor.js"></script>

    <link rel="stylesheet" href="~/css/Adminindex.css" asp-append-version="true" />
   


    
</head>
<body>
    <div class="container-fluid m-0 " style="width:100vw;">
        <div class="row d-flex">
            @*  <-----sidebar----->*@
            <div class="navigationbar col-2 col-xl-2 col-lg-3  col-md-1 d-none d-md-block  px-2  px-lg-2 px-md-0  ">
                <div class="mt-4 col-12  d-none d-lg-block">
                    <lable class="sideheader fw-bold fs-6 text-white text-break">Navigationbar</lable>
                </div>
                <ul class="nav nav-pills flex-column mb-auto mt-4 mt-lg-4 mt-md-5">

                    <li class="nav-item mt-2">
                        <a asp-action="Index" asp-controller="Admin" class="nav-link  sidebarcontent @(ViewBag.nav == 1? "active":"")" aria-current="page">

                            <i class="bi bi-person-fill   sidebar-img  "></i>
                            <lable class="d-block d-lg-block d-md-none">User</lable>
                        </a>
                    </li>
                    <li class="mt-2">
                        <a asp-action="AdminCms" asp-controller="Admin" class="nav-link sidebarcontent @(ViewBag.nav == 2? "active":"")">

                            <i class="bi bi-file-earmark-text-fill sidebar-img me-2"></i>

                            <lable class="d-block d-lg-block d-md-none">   CMS Page</lable>
                        </a>
                    </li>
                    <li class="mt-2">
                        <a asp-action="AdminMission" asp-controller="Admin" class="nav-link sidebarcontent @(ViewBag.nav == 3? "active":"")">

                            <i class="bi bi-bullseye sidebar-img me-2"></i>

                            <lable class="d-block d-lg-block d-md-none">  Mission</lable>
                        </a>
                    </li>
                    <li class="mt-2">
                        <a asp-action="AdminTheme" asp-controller="Admin" class="nav-link  sidebarcontent @(ViewBag.nav == 4? "active":"")">


                            <i class="bi bi-grid-1x2-fill sidebar-img me-2"></i>

                            <lable class="d-block d-lg-block d-md-none">Mission Theme</lable>
                        </a>
                    </li>
                    <li class="mt-2">
                        <a asp-action="AdminSkills" asp-controller="Admin" class="nav-link sidebarcontent @(ViewBag.nav == 5? "active":"")">

                            <i class="bi bi-tools sidebar-img me-2"></i>

                            <lable class="d-block d-lg-block d-md-none">Mission Skills</lable>
                        </a>
                    </li>
                    <li class="mt-2">
                        <a asp-action="AdminMissionApplication" asp-controller="Admin" class="nav-link sidebarcontent @(ViewBag.nav == 6? "active":"") ">

                            <i class="bi bi-folder-fill sidebar-img me-2"></i>

                            <lable class="d-block d-lg-block d-md-none">Mission Application</lable>
                        </a>
                    </li>
                    <li class="mt-2">
                        <a asp-action="AdminStory" asp-controller="Admin" class="nav-link  sidebarcontent @(ViewBag.nav == 7? "active":"")">

                            <i class="bi bi-book-half sidebar-img me-2"></i>

                            <lable class="d-block d-lg-block d-md-none">Story</lable>
                        </a>
                    </li>
                    <li class="mt-2">
                        <a asp-action="AdminBannerManagement" asp-controller="Admin" class="nav-link  sidebarcontent @(ViewBag.nav == 8? "active":"")">

                            <i class="bi bi-border-style sidebar-img me-2"></i>

                            <lable class="d-block d-lg-block d-md-none">Banner Management</lable>
                        </a>
                    </li>

                </ul>
            </div>
            <div class="col-12 col-xl-10 col-lg-9 col-md-11  ">
                <div class="row  shadow-lg " style="height:50px;">
                    <div class="col-12 d-flex bg-white ">
                        <div class="col-3  d-block d-md-none d-flex align-items-center">
                            <button class="border-0 bg-white" type="button" data-bs-toggle="offcanvas" data-bs-target="#Adminoffcanvas" aria-controls="offcanvasWithBothOptions">
                                <i class="bi bi-list " style="font-size:40px;"></i>
                            </button>


                        </div>
                        <div class="col-6 d-flex align-items-center" >
                            <p id="dashboadtime"></p>
                        </div>
                        <div class="col-6 d-none d-md-block">
                            <div class="dropdown  d-flex justify-content-end  ">
                                <button class="btn ms-auto me-3 dropdown-toggle  " type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    <img src="~/images/user1.png" alt="mdo" width="40" height="40" class="rounded-circle loginimg">
                                    Dropdown button
                                </button>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="#">Action</a></li>
                                    <li><a class="dropdown-item" href="#">Another action</a></li>
                                    <li><a class="dropdown-item" href="#">Something else here</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row" id="Views" style="">

                    @RenderBody()


                </div>

            </div>

        </div>
        <div class="d-block d-md-none offcanvas offcanvas-start adminofcanvasdiv h-100" data-bs-scroll="true" tabindex="-1" id="Adminoffcanvas" aria-labelledby="offcanvasWithBothOptionsLabel">
            <div class="offcanvas-header">
                <h5 class="offcanvas-title fw-bold fs-6 text-white text-break" id="offcanvasWithBothOptionsLabel">NAVIGATION  </h5>
                <button type="button" class="border-0" data-bs-dismiss="offcanvas" aria-label="Close" style="background-color:#F88634;">
                    <i class="bi bi-x-lg"></i>
                </button>
            </div>
            <div class="offcanvas-body">
                <div class="dropdown">
                    <button class="btn  dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="~/images/user1.png" alt="mdo" width="40" height="40" class="rounded-circle loginimg">
                        <span class="text-white">Dropdown button</span>
                    </button>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </div>

                <ul class="nav nav-pills flex-column mb-auto mt-3">

                    <li class="nav-item">
                        <a href="#1" class="nav-link  sidebarcontent active  " aria-current="page">

                            <i class="bi bi-person-fill   sidebar-img  "></i>
                            <lable class="d-block d-lg-block d-md-none">User</lable>
                        </a>
                    </li>
                    <li>
                        <a href="#2" class="nav-link sidebarcontent  ">

                            <i class="bi bi-file-earmark-text-fill sidebar-img me-2"></i>

                            <lable class="d-block d-lg-block d-md-none">   CMS Page</lable>
                        </a>
                    </li>
                    <li>
                        <a href="#3" class="nav-link  sidebarcontent">

                            <i class="bi bi-bullseye sidebar-img me-2"></i>

                            <lable class="d-block d-lg-block d-md-none">  Mission</lable>
                        </a>
                    </li>
                    <li>
                        <a href="#4" class="nav-link  sidebarcontent">


                            <i class="bi bi-grid-1x2-fill sidebar-img me-2"></i>

                            <lable class="d-block d-lg-block d-md-none">Mission Theme</lable>
                        </a>
                    </li>
                    <li>
                        <a href="#5" class="nav-link sidebarcontent">

                            <i class="bi bi-tools sidebar-img me-2"></i>

                            <lable class="d-block d-lg-block d-md-none">Mission Skills</lable>
                        </a>
                    </li>
                    <li>
                        <a href="#6" class="nav-link sidebarcontent ">

                            <i class="bi bi-folder-fill sidebar-img me-2"></i>

                            <lable class="d-block d-lg-block d-md-none">Mission Application</lable>
                        </a>
                    </li>
                    <li>
                        <a href="#7" class="nav-link  sidebarcontent">

                            <i class="bi bi-book-half sidebar-img me-2"></i>

                            <lable class="d-block d-lg-block d-md-none">Story</lable>
                        </a>
                    </li>
                    <li>
                        <a href="#8" class="nav-link  sidebarcontent">

                            <i class="bi bi-border-style sidebar-img me-2"></i>

                            <lable class="d-block d-lg-block d-md-none">Banner Management</lable>
                        </a>
                    </li>

                </ul>

            </div>
        </div>




    </div>





    <link rel="stylesheet" href="~/css/Adminindex.css" asp-append-version="true" />

    <script src="~/js/Admin.js" asp-append-version="true">

    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>




</body>
</html>

CI/CI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CI_platform</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/CI_platform.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~"/>
</head>
<body>
   
  
        
            @RenderBody()
    
   

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CI/CI/Views/Shared/_Nomission_PartialView.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="~/css/nomission.css"  asp-append-version="true"/>
</head>
<body>

    <div class=" container text-center no-mission  ">
        <h1> No Mission found</h1>
        <a type="button" class="btn submitnew  mt-2 mb-2" aspi-area="" asp-controller="Home" asp-action="landingpage">
            Submit New Mission
            <img src="~/images/right-arrow.png" />
        </a>

    </div>

</body>
</html>

CI/CI/Views/Shared/_navbar2.cshtml
@{
    var id = Context.Session.GetString("userID");
    var firstname = Context.Session.GetString("Firstname");
    var useravtar = Context.Session.GetString("useravtar");
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Navbar</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"  /*@>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <link rel="stylesheet" href="~/css/navbar.css" asp-append-version="true">




</head>
<body>
    <div id="preloader">
    </div>
    <div class=" mainheader fixed-top">

        <nav class="navbar navbar-expand-md navbar-light  header  pb-1" aria-label="Eighth navbar example">
            <div class="container">

                <button class="btn  hamburger " type="button" data-bs-toggle="offcanvas"
                        data-bs-target="#offcanvasWithBothOptions" aria-controls="offcanvasWithBothOptions">
                    <img src="~/images/list1.png">
                </button>


                <div class="offcanvas offcanvas-start" data-bs-scroll="true" tabindex="-1" id="offcanvasWithBothOptions"
                     aria-labelledby="offcanvasWithBothOptionsLabel">
                    <div class="offcanvas-header">
                        <h2 class="mt-2 me-2">CI-PLATFORM</h2>
                        <button type="button" class="btn-close " data-bs-dismiss="offcanvas" aria-label="Close"></button>
                    </div>
                    <div class="offcanvas-body navbar-nav me-auto mb-2 mb-lg-0 align-self-center">

                        @if (id == null)
                        {
                            <a class="col-12" href="/Login/Login"><button class="btn btn-primary w-100">Login</button></a>
                            <a class="mt-2 col-12" href="/User/register"><button class="btn btn-success w-100">Register</button></a>

                        }
                        else
                        {


                            <div class=" dropdown text-end ">
                                <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" data-bs-toggle="dropdown"
                                   aria-expanded="false">
                                    @if (useravtar != null)
                                    {
                                        <img src="@useravtar" alt="mdo" width="40" height="40" class=" loginimg rounded-circle">
                                    }
                                    else
                                    {
                                        <img src="~/images/user1.png" alt="mdo" width="40" height="40" class=" loginimg rounded-circle">
                                    }

                                    @* <span class="txt text-dark">Evan Donohue</span>*@


                                    @firstname
                                </a>
                                <ul class="dropdown-menu text-small">
                                    <li><a class="dropdown-item" href="#">New project...</a></li>
                                    <li><a class="dropdown-item" href="/Landingpage/Landingpage/@id">Dashboard</a></li>
                                    <li><a class="dropdown-item" href="/StoryListing/DraftStorys/@id">Draft Story</a></li>
                                    <li><a class="dropdown-item" href="/Volunteering/Volunteeringtimesheet/@id">Volunteering timesheet</a></li>
                                    <li><a class="dropdown-item" href="#">Settings</a></li>
                                    <li><a class="dropdown-item" href="/Home/Userprofile/@id">Profile</a></li>
                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>
                                    <li><a class="dropdown-item" asp-controller="Login" asp-action="Logout">Sign out</a></li>
                                </ul>
                            </div>
                        }


                        @if (id == null)
                        {
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" onclick="alertmsg();">Story</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="/StoryListing/StoryListing/@ViewBag.UserId">Story</a>
                            </li>
                        }


                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">Policy</a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="#">Action</a></li>
                                <li><a class="dropdown-item" href="#">Another action</a></li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                        </li>
                    </div>
                </div>

                <h2 class="nav-brand ms-3 me-auto">CI-PLATFORM</h2>
                <ul class="navbar-nav  navbar1  me-auto mb-2 mb-lg-0 ">
                    @if (id == null)
                    {
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" onclick="alertmsg();">Story</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/StoryListing/StoryListing/@ViewBag.UserId">Story</a>
                        </li>
                    }


                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">Policy</a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="#">Action</a></li>
                            <li><a class="dropdown-item" href="#">Another action</a></li>
                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                        </ul>
                    </li>
                </ul>

                @if (id == null)
                {
                    <a class="ms-2 d-none d-md-block" href="/Login/Login"><button class="btn btn-primary">Login</button></a>
                    <a class="ms-2  d-none d-md-block" href="/User/register"><button class="btn btn-success">Register</button></a>

                }
                else
                {

                    <div class="dropdown text-end userprofile ">
                        <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            @if (useravtar != null)
                            {
                                <img src="@useravtar" alt="mdo" width="40" height="40" class="rounded-circle loginimg">
                            }
                            else
                            {
                                <img src="~/images/user1.png" alt="mdo" width="40" height="40" class="rounded-circle loginimg">
                            }

                            @*   <span class="txt text-dark">Evan Donohue</span>*@

                            @firstname
                        </a>
                        <ul class="dropdown-menu text-small">
                            <li><a class="dropdown-item" href="#">New project...</a></li>
                            <li><a class="dropdown-item" href="/Landingpage/Landingpage/@id">Dashboard</a></li>
                            <li><a class="dropdown-item" href="/StoryListing/DraftStorys/@id">Draft Story</a></li>
                            <li><a class="dropdown-item" href="/Volunteering/Volunteeringtimesheet/@id">Volunteering timesheet</a></li>
                            <li><a class="dropdown-item" href="#">Settings</a></li>
                            <li><a class="dropdown-item" href="/Home/Userprofile/@id">Profile</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" asp-controller="Login" asp-action="Logout">Sign out</a></li>
                        </ul>
                    </div>
                }

            </div>
        </nav>


 

    </div>


    <main>
        @RenderBody()
    </main>
    <script src="/js/Navbar.js" asp-append-version="true"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous">
    </script>
</body>
</html>